### ISSUE TITLE
not installing all sounds for Logic Pro X

### ISSUE THREAD

**Issue by rmanly** [carlashley/appleLoops#29] opened 2018-03-09 14:23 UTC
I've got GarageBand and Logic Pro X installed and some loops are showing as incomplete in Logic and refusing to install from appleLoops.py.

![screen shot 2018-03-08 at 10 11 50 am](https://user-images.githubusercontent.com/1110967/37211746-94759f04-2372-11e8-8026-d9ccfee2e193.png)

![screen shot 2018-03-08 at 10 12 20 am](https://user-images.githubusercontent.com/1110967/37211766-a3c9d808-2372-11e8-890f-4859462ba3e9.png)

![screen shot 2018-03-08 at 10 12 45 am](https://user-images.githubusercontent.com/1110967/37211786-b0c6379a-2372-11e8-8f70-f150b7d7c57d.png)

![screen shot 2018-03-08 at 10 12 58 am](https://user-images.githubusercontent.com/1110967/37211794-b4f70326-2372-11e8-876e-30e31d867a6c.png)

- Command used:

appleLoops.py --deployment -m -o

- Version:

2.2.0

- Debug log output:

Here is the entire log.
[appleLoops.log](https://github.com/carlashley/appleLoops/files/1797161/appleLoops.log)

Here is just that last bit of the log…

2018-03-09 07:50:00,739 - appleLoops - INFO - Downloading: MAContent10_Logic9Legacy.pkg (Package size: 2.37 GB  Install size: 3.08 GB)
2018-03-09 07:52:32,175 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_Logic9Legacy.pkg
2018-03-09 07:52:32,176 - appleLoops - INFO -   Installing: MAContent10_Logic9Legacy.pkg
2018-03-09 07:52:32,680 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:52:32,681 - appleLoops - DEBUG - Attempting to remove MAContent10_Logic9Legacy.pkg after install was not successful.
2018-03-09 07:52:32,921 - appleLoops - INFO - Downloading: JamPack4_Instruments.pkg (Package size: 422.55 MB  Install size: 696.51 MB)
2018-03-09 07:53:03,968 - appleLoops - DEBUG - Not in dry run, so attempting to install JamPack4_Instruments.pkg
2018-03-09 07:53:03,969 - appleLoops - INFO -   Installing: JamPack4_Instruments.pkg
2018-03-09 07:53:04,377 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:53:04,377 - appleLoops - DEBUG - Attempting to remove JamPack4_Instruments.pkg after install was not successful.
2018-03-09 07:53:04,589 - appleLoops - INFO - Downloading: JamPack1.pkg (Package size: 242.53 MB  Install size: 317.75 MB)
2018-03-09 07:53:24,375 - appleLoops - DEBUG - Not in dry run, so attempting to install JamPack1.pkg
2018-03-09 07:53:24,376 - appleLoops - INFO -   Installing: JamPack1.pkg
2018-03-09 07:53:24,739 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:53:24,739 - appleLoops - DEBUG - Attempting to remove JamPack1.pkg after install was not successful.
2018-03-09 07:53:24,954 - appleLoops - INFO - Downloading: MAContent10_GarageBand6Legacy.pkg (Package size: 1.11 GB  Install size: 1.31 GB)
2018-03-09 07:54:24,680 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_GarageBand6Legacy.pkg
2018-03-09 07:54:24,681 - appleLoops - INFO -   Installing: MAContent10_GarageBand6Legacy.pkg
2018-03-09 07:54:25,146 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:54:25,147 - appleLoops - DEBUG - Attempting to remove MAContent10_GarageBand6Legacy.pkg after install was not successful.
2018-03-09 07:54:25,387 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacyVoices.pkg (Package size: 287.41 MB  Install size: 295.58 MB)
2018-03-09 07:54:41,789 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacyVoices.pkg
2018-03-09 07:54:41,790 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacyVoices.pkg
2018-03-09 07:54:42,165 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:54:42,166 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacyVoices.pkg after install was not successful.
2018-03-09 07:54:42,385 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacy1.pkg (Package size: 427.61 MB  Install size: 446.54 MB)
2018-03-09 07:55:05,797 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacy1.pkg
2018-03-09 07:55:05,797 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacy1.pkg
2018-03-09 07:55:06,165 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:55:06,166 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacy1.pkg after install was not successful.
2018-03-09 07:55:06,389 - appleLoops - INFO - Downloading: Voices_Instruments.pkg (Package size: 241.81 MB  Install size: 278.64 MB)
2018-03-09 07:55:26,767 - appleLoops - DEBUG - Not in dry run, so attempting to install Voices_Instruments.pkg
2018-03-09 07:55:26,767 - appleLoops - INFO -   Installing: Voices_Instruments.pkg
2018-03-09 07:55:27,131 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:55:27,132 - appleLoops - DEBUG - Attempting to remove Voices_Instruments.pkg after install was not successful.
2018-03-09 07:55:27,354 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacyWorld.pkg (Package size: 550.92 MB  Install size: 604.89 MB)
2018-03-09 07:55:59,724 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacyWorld.pkg
2018-03-09 07:55:59,725 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacyWorld.pkg
2018-03-09 07:56:00,211 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:56:00,211 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacyWorld.pkg after install was not successful.
2018-03-09 07:56:00,453 - appleLoops - INFO - Downloading: MAContent10_IRsSurround.pkg (Package size: 483.28 MB  Install size: 856.50 MB)
2018-03-09 07:56:43,298 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_IRsSurround.pkg
2018-03-09 07:56:43,299 - appleLoops - INFO -   Installing: MAContent10_IRsSurround.pkg
2018-03-09 07:56:43,766 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:56:43,767 - appleLoops - DEBUG - Attempting to remove MAContent10_IRsSurround.pkg after install was not successful.
2018-03-09 07:56:44,014 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacySymphony.pkg (Package size: 624.86 MB  Install size: 658.73 MB)
2018-03-09 07:57:38,391 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacySymphony.pkg
2018-03-09 07:57:38,392 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacySymphony.pkg
2018-03-09 07:57:38,871 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:57:38,872 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacySymphony.pkg after install was not successful.
2018-03-09 07:57:39,123 - appleLoops - INFO - Downloading: RhythmSection_Instruments.pkg (Package size: 1.22 GB  Install size: 2.27 GB)
2018-03-09 07:59:12,296 - appleLoops - DEBUG - Not in dry run, so attempting to install RhythmSection_Instruments.pkg
2018-03-09 07:59:12,297 - appleLoops - INFO -   Installing: RhythmSection_Instruments.pkg
2018-03-09 07:59:12,743 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:59:12,744 - appleLoops - DEBUG - Attempting to remove RhythmSection_Instruments.pkg after install was not successful.
2018-03-09 07:59:12,989 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacyRhythm.pkg (Package size: 362.13 MB  Install size: 391.57 MB)
2018-03-09 07:59:42,058 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacyRhythm.pkg
2018-03-09 07:59:42,059 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacyRhythm.pkg
2018-03-09 07:59:42,428 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 07:59:42,429 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacyRhythm.pkg after install was not successful.
2018-03-09 07:59:42,650 - appleLoops - INFO - Downloading: RemixTools_Instruments.pkg (Package size: 484.28 MB  Install size: 673.77 MB)
2018-03-09 08:00:23,586 - appleLoops - DEBUG - Not in dry run, so attempting to install RemixTools_Instruments.pkg
2018-03-09 08:00:23,587 - appleLoops - INFO -   Installing: RemixTools_Instruments.pkg
2018-03-09 08:00:24,058 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 08:00:24,059 - appleLoops - DEBUG - Attempting to remove RemixTools_Instruments.pkg after install was not successful.
2018-03-09 08:00:24,303 - appleLoops - INFO - Downloading: MAContent10_AppleLoopsLegacyRemix.pkg (Package size: 392.26 MB  Install size: 425.58 MB)
2018-03-09 08:00:49,119 - appleLoops - DEBUG - Not in dry run, so attempting to install MAContent10_AppleLoopsLegacyRemix.pkg
2018-03-09 08:00:49,120 - appleLoops - INFO -   Installing: MAContent10_AppleLoopsLegacyRemix.pkg
2018-03-09 08:00:49,485 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 08:00:49,486 - appleLoops - DEBUG - Attempting to remove MAContent10_AppleLoopsLegacyRemix.pkg after install was not successful.
2018-03-09 08:00:49,708 - appleLoops - INFO - Downloading: WorldMusic_Instruments.pkg (Package size: 110.34 MB  Install size: 133.09 MB)
2018-03-09 08:00:58,469 - appleLoops - DEBUG - Not in dry run, so attempting to install WorldMusic_Instruments.pkg
2018-03-09 08:00:58,470 - appleLoops - INFO -   Installing: WorldMusic_Instruments.pkg
2018-03-09 08:00:58,764 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.

2018-03-09 08:00:58,765 - appleLoops - DEBUG - Attempting to remove WorldMusic_Instruments.pkg after install was not successful.
2018-03-09 08:00:58,785 - appleLoops - INFO - Skipping mainstage as it does not appear to be installed.
2018-03-09 08:00:58,785 - appleLoops - INFO - Installed 0 packages, downloaded 9.23 GB, install size 0.00 B
2018-03-09 08:00:58,786 - appleLoops - INFO - sys.exit(17) - Not all loops installed: MAContent10_Logic9Legacy.pkg, JamPack4_Instruments.pkg, JamPack1.pkg, MAContent10_GarageBand6Legacy.pkg, MAContent10_AppleLoopsLegacyVoices.pkg, MAContent10_AppleLoopsLegacy1.pkg, Voices_Instruments.pkg, MAContent10_AppleLoopsLegacyWorld.pkg, MAContent10_IRsSurround.pkg, MAContent10_AppleLoopsLegacySymphony.pkg, RhythmSection_Instruments.pkg, MAContent10_AppleLoopsLegacyRhythm.pkg, RemixTools_Instruments.pkg, MAContent10_AppleLoopsLegacyRemix.pkg, WorldMusic_Instruments.pkg

**Comment by rmanly** [comment] 2018-03-09 15:02
LPX can successfully install these remaining 9GB of loops.

![screen shot 2018-03-09 at 9 01 14 am](https://user-images.githubusercontent.com/1110967/37213715-80552df4-2378-11e8-8402-1ff43be6d138.png)

**Comment by carlashley** [comment] 2018-03-15 09:09
The error message you're getting:
```
2018-03-09 08:00:58,764 - appleLoops - DEBUG - Install does not appear to be successful: installer: Cannot install on volume / because it is disabled.
installer: A qualifying copy of Logic or MainStage was not found.
```
The packages supplied by Apple check to make sure that a qualifying copy of their audio apps is already installed. If the package is failing because of this, then the loop package itself doesn't think the qualifying app is installed on the system.

To verify, you should run `pkgutil --pkgs | grep -i logicpro`. If installed correctly via the App store, the following output should appear. I'm not sure what it will be for anything distributed via VPP deployment, possibly the same.
```
[user@pegasus]:jampack # pkgutil --pkgs | grep -i logicpro
com.apple.pkg.LogicProX_AppStore
```

If you're deploying those apps through some other means, or somehow the bundle identifier of the app is being mangled (it should be `com.apple.logic10`), then that might be why those packages aren't installing properly.

Try a fresh system (recommend a VM) with a fresh install of LP 10.x to test on.

I've done a test on a machine here with Logic Pro 10.4.x and can't replicate it.


[https://github.com/carlashley/appleLoops/wiki/Understanding-Apple's-Audio-Content](Understanding Apple's Audio Content)

**Comment by rmanly** [comment] 2018-03-19 14:01
Thanks for the reply.

The LPX install in question is from an institutional Apple ID, imported into Munki via autopkg.

I'll have some time to try again with a fresh download direct from the App Store tomorrow.

**Comment by carlashley** [comment] 2018-06-27 22:33
Just a note re this issue, I've tested GarageBand 10.3 deployment, and had the below list of loops error out. It doesn't appear to affect launching and running GarageBand 10.3.

```
2018-06-25 12:38:55,873 - appleLoops - INFO - sys.exit(17) - Not all loops installed:
MAContent10_Logic9Legacy.pkg, JamPack4_Instruments.pkg, JamPack1.pkg,
MAContent10_GarageBand6Legacy.pkg, MAContent10_AppleLoopsLegacyVoices.pkg,
MAContent10_AppleLoopsLegacy1.pkg, Voices_Instruments.pkg,
MAContent10_AppleLoopsLegacyWorld.pkg, MAContent10_IRsSurround.pkg,
MAContent10_AppleLoopsLegacySymphony.pkg, RhythmSection_Instruments.pkg,
MAContent10_AppleLoopsLegacyRhythm.pkg, RemixTools_Instruments.pkg,
MAContent10_AppleLoopsLegacyRemix.pkg, WorldMusic_Instruments.pkg
```

**Comment by TheBismarck** [comment] 2018-07-01 22:17
I have this issue too...  I have Logic X 10.4.1 which I do note isn't specifically listed in the script, only Logic 10.4.0 is. 

When I run AppleLoops with the -m and -o flags, it seems to want to install the same 7 "missing" loop packages each time... The output shows as successful as follows. If I re-run the script, even after rebooting, the same 7 download and install again.

Processing loops from: logicpro1040.plist
Downloading: MAContent10_AssetPack_0510_EXS_Strings.pkg (Package size: 55.73 MB  Install size: 67.54 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0510_EXS_Strings.pkg
  Installed: MAContent10_AssetPack_0510_EXS_Strings.pkg
Downloading: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg (Package size: 25.70 MB  Install size: 29.56 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
  Installed: MAContent10_AssetPack_0487_EXS_OrchWoodwindFluteSolo.pkg
Downloading: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg (Package size: 185.96 MB  Install size: 211.82 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
  Installed: MAContent10_AssetPack_0491_EXS_OrchBrass.pkg
Downloading: MAContent10_AssetPack_0489_EXS_OrchWoodwindOboeSolo.pkg (Package size: 29.39 MB  Install size: 32.49 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0489_EXS_OrchWoodwindOboeSolo.pkg
  Installed: MAContent10_AssetPack_0489_EXS_OrchWoodwindOboeSolo.pkg
Downloading: MAContent10_AssetPack_0483_EXS_OrchWoodwindBasson.pkg (Package size: 50.63 MB  Install size: 55.11 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0483_EXS_OrchWoodwindBasson.pkg
  Installed: MAContent10_AssetPack_0483_EXS_OrchWoodwindBasson.pkg
Downloading: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg (Package size: 27.73 MB  Install size: 31.58 MB)
######################################################################## 100.0%
  Installing: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
  Installed: MAContent10_AssetPack_0484_EXS_OrchWoodwindClarinetSolo.pkg
Downloading: JamPack1.pkg (Package size: 12.20 MB  Install size: 317.75 MB)
######################################################################## 100.0%
  Installing: JamPack1.pkg
  Installed: JamPack1.pkg
Skipping mainstage as it does not appear to be installed.
Installed 7 packages, downloaded 387.33 MB, install size 745.84 MB

In case the loops are possibly corrupt on my local mirror, I run Logic X and get that application to "download" the missing loops and I copy them from the obfuscated path in /var/folders and put them in my local mirror thus replacing any possible corrupt copies... Same issue.

Now when I run the pkgutil command, I get no response because LogicPro was installed using VPP Apple ID, which was deployed with Munki... However AppleLoops does still detect Logic installed and is version 10.4.0.

**Comment by TheBismarck** [comment] 2018-07-01 22:40
Oh... I can confirm that if I let Logic X install the "missing" loops using the Logic GUI, the loops install fine, and Logic now shows all loops installed, and the script doesn't detect any loops as missing any more.

**Comment by carlashley** [comment] 2018-07-01 23:17
Loops for Logic Pro X (v 10.4.1) haven't changed according to the version I've got on my machine; the plist is still `logicpro1040.plist`.

**Comment by TheBismarck** [comment] 2018-07-01 23:34
OK, I've done some more investigation... and I think I've got to the bottom of it...

So, I mentioned that my AppleLoops script was trying to "redownload" the same missing loops over and over again... And Logic would still show those loops as "missing".

Next, I allowed Logic to download the "missing" loops, and before Logic installs them, I grab the copies of the loops from /var/folders/xxxx and copy them to my Local Mirror... I said that bit didn't solve the problem earlier, but it does (I have 3x local mirrors and I copied them to the wrong one for testing)...

So on the server, I re-run the AppleLoops command to update the Local Mirror from Apple's servers, and this bit seems to not work I don't think... Even though I update the Local Mirror directly using AppleLoops, Logic will still find the same loops missing. But if I manually update the Local Mirror using copies that Logic downloads, then the loops install fine.

So where I think the problem is that perhaps the mechanism that AppleLoops uses to checking if any loop packages have been updated may not be entirely reliable...

**Comment by carlashley** [comment] 2018-07-02 04:17
You can delete the loops that are causing an issue and re-download them. It's entirely possible that Apple have recently made changes to those particular loops and the older ones aren't "compatible".

I haven't had a chance to grab them from Apple yet to see if the SHA's are different.

**Comment by carlashley** [comment] 2018-07-03 03:30
In relation to loop content not installing for GarageBand 10.3+, if an install attempt occurs for the pkgs listed below, it will fail as GarageBand isn't a qualifying app for those loops.
Will dig deeper into why these are being downloaded and installed.

```
JamPack1.pkg
JamPack4_Instruments.pkg
MAContent10_AppleLoopsLegacy1.pkg
MAContent10_AppleLoopsLegacyRemix.pkg
MAContent10_AppleLoopsLegacyRhythm.pkg
MAContent10_AppleLoopsLegacySymphony.pkg
MAContent10_AppleLoopsLegacyVoices.pkg
MAContent10_AppleLoopsLegacyWorld.pkg
MAContent10_GarageBand6Legacy.pkg
MAContent10_IRsSurround.pkg
MAContent10_Logic9Legacy.pkg
RemixTools_Instruments.pkg
RhythmSection_Instruments.pkg
Voices_Instruments.pkg
WorldMusic_Instruments.pkg
```

**Comment by carlashley** [comment] 2018-07-03 07:47
So I've tested the installation of the loops per comment [here](https://github.com/carlashley/appleLoops/issues/29#issuecomment-402002580).

With Logic Pro X and MainStage 3 installed, those loops will install perfectly fine. The issue with those loops not installing when only GarageBand is installed is simply due to GarageBand not being a qualifying app. I'd hazard a guess this _may_ be an issue for Apple to resolve (either by removing the loops from the `garageband1021.plist` (and possibly from other relevant GarageBand plists).

@rmanly if you can test [v2.2.2](https://github.com/carlashley/appleLoops/releases/tag/v2.2.2) out, that would be great.

I'm pretty sure this issue can be closed out, will just wait for confirmation before doing so.

**Comment by carlashley** [comment] 2018-07-07 10:56
I'm now marking this as closed, have run several tests with GarageBand 10.3.x without issue.

**Closed by carlashley** 2018-07-07 10:56 UTC

**Comment by a-zaleski** [comment] 2018-07-20 16:12
Sorry to revive this issue again, but I was running into a problem on a fresh macOS install with the latest GarageBand and appleLoops versions and a brand new local mirror. I saw this in the commits: https://github.com/carlashley/appleLoops/commit/06cbe81cbe58c04dc0cd5e82a990aafab6e41340.

I believe you meant to include 'JamPack1.pkg' in that list and exclude 'MAContent10_AssetPack_0326_AppleLoopsJamPack1.pkg'. If you open both packages in [Suspicious Package](https://www.mothersruin.com/software/SuspiciousPackage/) and have the 'Distribution script' option checked in the preferences, you'll see that 'JamPack1.pkg' checks for the existence of Logic or Mainstage. I made the changes to the list locally and had the script run successfully.

**Comment by carlashley** [comment] 2018-08-05 13:15
Hey @a-zaleski - thanks for the eagle eye there and sorry for the late reply. I double checked to make sure I have the correct package, and can confirm `MAContent10_AssetPack_0326_AppleLoopsJamPack1.pkg` is in the list of "bad packages" .

If I remember rightly I had the wrong filename in one commit, and the commit https://github.com/carlashley/appleLoops/commit/06cbe81cbe58c04dc0cd5e82a990aafab6e41340 fixed that problem.

**Comment by carlashley** [comment] 2018-08-05 13:28
@a-zaleski cheers - should be resolved now per https://github.com/carlashley/appleLoops/commit/173c2b98f09c557fd27eb5c4629ab7f0d74b3ab6
